name: Build & Release FlyEnv (Windows)

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'src/helper-go/go.mod'
          cache-dependency-path: 'src/helper-go/go.sum'

      - name: Enable Yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            **/node_modules
            .yarn/cache
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install deps
        run: |
          npm install -g node-gyp
          yarn install --frozen-lockfile

      - name: Build Go helper
        run: |
          go install github.com/tc-hib/go-winres@latest
          $GOBIN = (go env GOPATH) + "\bin"
          $env:PATH = "$GOBIN;$env:PATH"

          cd src/helper-go
          go mod download
          go-winres make
          .\build-win.ps1

      - name: Build + Publish Electron
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn build
